# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WgG070Acv1kJFq8q9-6ZF_I-CU7_qAvC
"""

import os
import numpy as np
import scipy.special as special
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader, random_split

# =====================================================================
# SECTION 1: PHYSICAL SIMULATION & DATA GENERATION
# =====================================================================

def generate_diffraction_pattern(wavelength, R=1e-4, z=1.0, grid_size=128):
    """
    Simulates the forward physics model: Fraunhofer diffraction of a circular aperture.
    Uses the first-order Bessel function of the first kind to compute intensity profile.
    """
    # Spatial coordinates of the observation screen (4x4 cm area)
    x = np.linspace(-0.02, 0.02, grid_size)
    y = np.linspace(-0.02, 0.02, grid_size)
    X, Y = np.meshgrid(x, y)
    r = np.sqrt(X**2 + Y**2) + 1e-12  # Avoid division by zero

    # Wave vector calculation
    k = (2 * np.pi) / wavelength
    sin_theta = r / z
    arg = k * R * sin_theta

    # Airy disk intensity distribution formula
    intensity = (2 * special.j1(arg) / arg) ** 2

    # Min-max normalization to fit scale [0, 1] for robust neural network convergence
    intensity = intensity / np.max(intensity)
    return intensity

def build_dataset(num_samples=5000, grid_size=128):
    """
    Generates synthetic dataset spanning the visible spectrum (400nm to 700nm).
    Saves tensors into a reusable PyTorch checkpoint.
    """
    print("Initializing synthetic dataset generation...")
    # Uniform sampling across the visible light spectrum
    wavelengths = np.random.uniform(400e-9, 700e-9, num_samples)

    X_data = np.zeros((num_samples, grid_size, grid_size), dtype=np.float32)
    Y_data = np.zeros((num_samples, 1), dtype=np.float32)

    for i in range(num_samples):
        X_data[i] = generate_diffraction_pattern(wavelengths[i])
        # Scale target feature by 1e7 for optimal gradient updates during training
        Y_data[i] = wavelengths[i] * 1e7

    # Cast to PyTorch tensors and save locally
    torch.save((torch.tensor(X_data), torch.tensor(Y_data)), 'dataset.pt')
    print(f"Successfully generated and cached {num_samples} physical patterns in 'dataset.pt'.\n")

# =====================================================================
# SECTION 2: NEURAL NETWORK ARCHITECTURE DEFINITION
# =====================================================================

class OpticsCNN(nn.Module):
    """
    Convolutional Neural Network designed to solve the optical inverse problem.
    Extracts geometric spatial features (Airy rings) to predict the physical wavelength.
    """
    def __init__(self):
        super(OpticsCNN, self).__init__()

        # Deep feature extraction network
        self.features = nn.Sequential(
            # Layer 1: Input size [Batch, 1, 128, 128] -> Output [Batch, 16, 64, 64]
            nn.Conv2d(1, 16, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            # Layer 2: Input size [Batch, 16, 64, 64] -> Output [Batch, 32, 32, 32]
            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            # Layer 3: Input size [Batch, 32, 32, 32] -> Output [Batch, 64, 16, 16]
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)
        )

        # Regression network for continuous target optimization
        self.regressor = nn.Sequential(
            nn.Linear(64 * 16 * 16, 128),
            nn.ReLU(),
            nn.Linear(128, 1) # Output layer mapping to a single continuous real value
        )

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), -1)  # Flatten spatial feature maps into a 1D vector
        x = self.regressor(x)
        return x

# =====================================================================
# SECTION 3: PIPELINE EXECUTION, TRAINING & EVALUATION
# =====================================================================

def run_pipeline():
    # Setup execution hardware target (GPU acceleration if available)
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Execution environment configured. Target device: {device}")

    # Check for dataset existence; generate if missing
    if not os.path.exists('dataset.pt'):
        build_dataset()

    X, Y = torch.load('dataset.pt')
    X = X.unsqueeze(1)  # Expand dimensions to include single color channel [B, C, H, W]

    # Execute deterministic random split for train (80%) and validation/test (20%) datasets
    dataset = TensorDataset(X, Y)
    num_samples = len(dataset)
    train_size = int(0.8 * num_samples)
    test_size = num_samples - train_size
    train_dataset, test_dataset = random_split(dataset, [train_size, test_size])

    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

    # Model instantiation
    model = OpticsCNN().to(device)
    criterion = nn.MSELoss()  # Standard Mean Squared Error loss for physical regression tasks
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    train_losses = []
    test_losses = []
    num_epochs = 15

    # --- Model Optimization Loop ---
    print("Commencing network optimization loop...")
    for epoch in range(num_epochs):
        model.train()
        running_train_loss = 0.0
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_train_loss += loss.item() * images.size(0)

        epoch_train_loss = running_train_loss / train_size
        train_losses.append(epoch_train_loss)

        # End-of-epoch validation tracking
        model.eval()
        running_test_loss = 0.0
        with torch.no_grad():
            for images, labels in test_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)
                loss = criterion(outputs, labels)
                running_test_loss += loss.item() * images.size(0)

        epoch_test_loss = running_test_loss / test_size
        test_losses.append(epoch_test_loss)

        print(f"Epoch {epoch+1:02d}/{num_epochs} | Train Loss: {epoch_train_loss:.5f} | Test Loss: {epoch_test_loss:.5f}")

    # --- Metric Evaluation and Visualization Generation ---
    print("\nTraining complete. Starting out-of-sample statistical evaluation...")
    model.eval()
    all_preds, all_labels = [], []

    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            all_preds.extend(outputs.cpu().numpy().flatten())
            all_labels.extend(labels.cpu().numpy().flatten())

    # Revert target scaling to map targets directly back to real nanometers (nm)
    all_preds_nm = np.array(all_preds) * 100
    all_labels_nm = np.array(all_labels) * 100

    # Absolute metrics calculation
    mae = np.mean(np.abs(all_preds_nm - all_labels_nm))
    print(f"\n>> Evaluation Metric Check: Test Mean Absolute Error (MAE) = {mae:.2f} nm\n")

    # 1. Export Loss Convergence Figure
    plt.figure(figsize=(8, 5))
    plt.plot(range(1, num_epochs+1), train_losses, marker='o', color='#2980b9', linewidth=2, label='Training Loss')
    plt.plot(range(1, num_epochs+1), test_losses, marker='s', color='#27ae60', linewidth=2, label='Validation Loss')
    plt.title('Model Training & Validation Convergence Profiles', fontsize=12, fontweight='bold', pad=15)
    plt.xlabel('Optimization Epochs', fontsize=10)
    plt.ylabel('Loss Metrics (MSE)', fontsize=10)
    plt.grid(True, linestyle=':', alpha=0.6)
    plt.legend(fontsize=10)
    plt.tight_layout()
    plt.savefig('loss_curve.png', dpi=300)
    plt.show()
    plt.close()

    # 2. Export Parity (True vs Predicted) Verification Plot
    plt.figure(figsize=(7, 6))
    plt.scatter(all_labels_nm, all_preds_nm, color='#2c3e50', alpha=0.5, edgecolors='w', label='AI Predictions')
    plt.plot([400, 700], [400, 700], color='#e74c3c', linestyle='--', linewidth=2, label='Identity Line ($y=x$)')
    plt.title('Parity Analysis: AI Predicted Wavelength vs. Ground Truth', fontsize=12, fontweight='bold', pad=15)
    plt.xlabel('Ground Truth Wavelength (nm)', fontsize=10)
    plt.ylabel('Model Estimated Wavelength (nm)', fontsize=10)
    plt.xlim(380, 720)
    plt.ylim(380, 720)
    plt.grid(True, linestyle=':', alpha=0.6)
    plt.legend(fontsize=10)
    plt.tight_layout()
    plt.savefig('true_vs_predicted.png', dpi=300)
    plt.show()
    plt.close()
    print("Diagnostic figures generated and saved successfully to disk.")

if __name__ == "__main__":
    run_pipeline()